services:
  app:
    image: my-multi-service-app:latest
    container_name: my-multi-service-app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
    networks:
      - my-network

  mongodb:
    image: mongo:6.0
    container_name: my-mongodb
    ports:
      - "27017:27017"
    networks:
      - my-network

  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
